export const FETCH_HOME_TEXT_CONTENT = "FETCH_HOME_TEXT_CONTENT";
export const FETCH_SPEAKER_CONTENT = "FETCH_SPEAKER_CONTENT";
export const FETCH_SPONSOR_CONTENT = "FETCH_SPONSOR_CONTENT";
export const FETCH_PAST_EVENTS_CONTENT = "FETCH_PAST_EVENTS_CONTENT";
