export const SET_HOME_TEXT_CONTENT = "SET_HOME_TEXT_CONTENT";
export const SET_SPEAKER_CONTENT = "SET_SPEAKER_CONTENT";
export const SET_SPONSOR_CONTENT = "SET_SPONSOR_CONTENT";
export const SET_PAST_EVENTS_CONTENT = "SET_PAST_EVENTS_CONTENT";
